version: "3.7"

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - DB_SQLITE_VACUUM_ON_STARTUP=true
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=n8n.local
      - N8N_PORT=5678
      - WEBHOOK_URL=http://localhost:5678/
      - TZ=America/Sao_Paulo
    volumes:
      - ./n8n_data:/home/node/.n8n
