version: '3.8'

services:
  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - .//html:/usr/share/nginx/html:ro
      - ./conf.d:/etc/nginx/conf.d:ro
    restart: always
